server:
  port: 9010
spring:
  application:
    name: tensquare-friend #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.130:3306/tensquare_friend?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.199.130
  rabbitmq:
    host: 192.168.199.130
jwt:
    config:
      key: itcast
      ttl: 360000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
